# Generated by Django 3.0.4 on 2020-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_difficulty_field_to_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default=1),
        ),
    ]
