# Generated by Django 3.0.4 on 2020-03-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_add_rate_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rate_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rate_points',
        ),
    ]
