# Generated by Django 3.0.4 on 2020-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe.jpg', upload_to='recipe_pics'),
        ),
    ]
