# Generated by Django 3.0.4 on 2020-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Hard')], default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe.jpeg', upload_to='recipe_pics'),
        ),
    ]
