# Generated by Django 3.0.4 on 2020-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_delete_rate_and_like_fields_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Ingredient'),
        ),
    ]
